<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build
// Modified by Defri Indra
// 2021

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "t_smarthome".
 *
 * @property integer $id_user
 * @property string $nama
 * @property string $suhu
 * @property string $kelembapan
 * @property string $tegangan
 * @property string $daya
 * @property string $ampere
 * @property string $daya_sebelumnya
 * @property string $ampere_sebelumnya
 * @property string $token
 * @property integer $flag
 * @property integer $id
 *
 * @property \app\models\SmarthomeKontrol[] $smarthomeKontrols
 * @property \app\models\SmarthomeSirkuit[] $smarthomeSirkuits
 * @property string $aliasModel
 */
abstract class Smarthome extends \yii\db\ActiveRecord
{
    /**
     * BaseModel rules. 
     **/
    use \app\traits\ModelTrait;

    const SCENARIO_CREATE = 'create';
    const SCENARIO_UPDATE = 'update';
    public $_render = [];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 't_smarthome';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => \app\components\behaviors\UUIDBehavior::class,
                'model' => get_called_class(),
                'primaryKey' => 'id',
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_user', 'nama', 'daya', 'ampere', 'daya_sebelumnya', 'ampere_sebelumnya', 'token'], 'required'],
            [['id_user', 'flag'], 'integer'],
            [['nama', 'token'], 'string', 'max' => 100],
            [['suhu', 'kelembapan', 'tegangan', 'daya', 'ampere', 'daya_sebelumnya', 'ampere_sebelumnya'], 'string', 'max' => 10],
            [['id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_user' => 'User',
            'nama' => 'Nama',
            'suhu' => 'Suhu',
            'kelembapan' => 'Kelembapan',
            'tegangan' => 'Tegangan',
            'daya' => 'Daya',
            'ampere' => 'Ampere',
            'daya_sebelumnya' => 'Daya Sebelumnya',
            'ampere_sebelumnya' => 'Ampere Sebelumnya',
            'token' => 'Token',
            'flag' => 'Flag',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSmarthomeKontrols()
    {
        return $this->hasMany(\app\models\SmarthomeKontrol::class, ['id_smarthome' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSmarthomeSirkuits()
    {
        return $this->hasMany(\app\models\SmarthomeSirkuit::class, ['id_smarthome' => 'id']);
    }





    public function scenarios()
    {
        $parent = parent::scenarios();

        $columns = [
            'id',
            'id_user',
            'nama',
            'suhu',
            'kelembapan',
            'tegangan',
            'daya',
            'ampere',
            'daya_sebelumnya',
            'ampere_sebelumnya',
            'token',
            'flag',
        ];

        $parent[static::SCENARIO_CREATE] = $columns;
        $parent[static::SCENARIO_UPDATE] = $columns;
        return $parent;
    }

    /**
     * @inheiritance
     */
    public function fields()
    {
        $parent = parent::fields();

        if(isset($parent['id'])) :
            unset($parent['id']);
            $parent['id'] = function($model) {
                return $model->id;
            };
        endif;
        if(isset($parent['id_user'])) :
            unset($parent['id_user']);
            $parent['id_user'] = function($model) {
                return $model->id_user;
            };
        endif;
        if(isset($parent['nama'])) :
            unset($parent['nama']);
            $parent['nama'] = function($model) {
                return $model->nama;
            };
        endif;
        if(isset($parent['suhu'])) :
            unset($parent['suhu']);
            $parent['suhu'] = function($model) {
                return $model->suhu;
            };
        endif;
        if(isset($parent['kelembapan'])) :
            unset($parent['kelembapan']);
            $parent['kelembapan'] = function($model) {
                return $model->kelembapan;
            };
        endif;
        if(isset($parent['tegangan'])) :
            unset($parent['tegangan']);
            $parent['tegangan'] = function($model) {
                return $model->tegangan;
            };
        endif;
        if(isset($parent['daya'])) :
            unset($parent['daya']);
            $parent['daya'] = function($model) {
                return $model->daya;
            };
        endif;
        if(isset($parent['ampere'])) :
            unset($parent['ampere']);
            $parent['ampere'] = function($model) {
                return $model->ampere;
            };
        endif;
        if(isset($parent['daya_sebelumnya'])) :
            unset($parent['daya_sebelumnya']);
            $parent['daya_sebelumnya'] = function($model) {
                return $model->daya_sebelumnya;
            };
        endif;
        if(isset($parent['ampere_sebelumnya'])) :
            unset($parent['ampere_sebelumnya']);
            $parent['ampere_sebelumnya'] = function($model) {
                return $model->ampere_sebelumnya;
            };
        endif;
        if(isset($parent['token'])) :
            unset($parent['token']);
            $parent['token'] = function($model) {
                return $model->token;
            };
        endif;
        if(isset($parent['flag'])) :
            unset($parent['flag']);
            $parent['flag'] = function($model) {
                return $model->flag;
            };
        endif;


    // $parent['smarthome_kontrol'] = function($model) {
    //     $rel = $model->smarthomeKontrols;
    //     if($rel) :
    //         return $rel;
    //     endif;
    //     return null;
    // };
    // $parent['smarthome_sirkuit'] = function($model) {
    //     $rel = $model->smarthomeSirkuits;
    //     if($rel) :
    //         return $rel;
    //     endif;
    //     return null;
    // };

        return $parent;
    }


    public static function faker($count = 10){
        $faker= \Faker\Factory::create();
        $faker->addProvider(new \app\components\faker\provider\MyImage($faker));
        $data = [];
        $maxId = static::find()->max('id');

        // relational data
        for ($i = 0; $i < $count; $i++) {
            $data[] = [ 
                "id_user" => $faker->unique()->numberBetween($maxId, $maxId + $count),
                "nama" => $faker->name,
                "suhu" => $faker->text(),
                "kelembapan" => $faker->text(),
                "tegangan" => $faker->text(),
                "daya" => $faker->text(),
                "ampere" => $faker->text(),
                "daya_sebelumnya" => $faker->text(),
                "ampere_sebelumnya" => $faker->text(),
                "token" => $faker->text(),
                "flag" => $faker->numberBetween(0, 1),
                "id" => $faker->unique()->numberBetween($maxId, $maxId + $count),
            ];
        }
        return $data;
    }

}
