<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use ;

/**
 * This is the base-model class for table "t_smarthome_kontrol".
 *
 * @property integer $id_smarthome
 * @property integer $id_sirkuit
 * @property string $ikon
 * @property string $nama
 * @property string $pin
 * @property integer $value
 * @property string $created_at
 * @property integer $flag
 * @property integer $id
 *
 * @property \app\models\TSmarthomeSirkuit $sirkuit
 * @property \app\models\TSmarthome $smarthome
 * @property string $aliasModel
 */
abstract class SmarthomeKontrol extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 't_smarthome_kontrol';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_smarthome', 'nama', 'pin', 'value'], 'required'],
            [['id_smarthome', 'id_sirkuit', 'value', 'flag'], 'integer'],
            [['created_at'], 'safe'],
            [['ikon'], 'string', 'max' => 255],
            [['nama'], 'string', 'max' => 150],
            [['pin'], 'string', 'max' => 20],
            [['id'], 'unique'],
            [['id_smarthome'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TSmarthome::class, 'targetAttribute' => ['id_smarthome' => 'id']],
            [['id_sirkuit'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TSmarthomeSirkuit::class, 'targetAttribute' => ['id_sirkuit' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_smarthome' => 'Id Smarthome',
            'id_sirkuit' => 'Id Sirkuit',
            'ikon' => 'Ikon',
            'nama' => 'Nama',
            'pin' => 'Pin',
            'value' => 'Value',
            'created_at' => 'Created At',
            'flag' => 'Flag',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSirkuit()
    {
        return $this->hasOne(\app\models\TSmarthomeSirkuit::class, ['id' => 'id_sirkuit']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSmarthome()
    {
        return $this->hasOne(\app\models\TSmarthome::class, ['id' => 'id_smarthome']);
    }




}
