<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use ;

/**
 * This is the base-model class for table "t_smarthome_master_produk_pair".
 *
 * @property integer $id_master_produk
 * @property string $kode_pairing
 * @property string $created_at
 * @property string $expired_at
 * @property integer $flag
 * @property integer $id
 *
 * @property \app\models\TSmarthomeMasterProduk $masterProduk
 * @property string $aliasModel
 */
abstract class SmarthomeMasterProdukPair extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 't_smarthome_master_produk_pair';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_master_produk', 'kode_pairing'], 'required'],
            [['id_master_produk', 'flag'], 'integer'],
            [['created_at', 'expired_at'], 'safe'],
            [['kode_pairing'], 'string', 'max' => 25],
            [['id'], 'unique'],
            [['id_master_produk'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TSmarthomeMasterProduk::class, 'targetAttribute' => ['id_master_produk' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_master_produk' => 'Id Master Produk',
            'kode_pairing' => 'Kode Pairing',
            'created_at' => 'Created At',
            'expired_at' => 'Expired At',
            'flag' => 'Flag',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMasterProduk()
    {
        return $this->hasOne(\app\models\TSmarthomeMasterProduk::class, ['id' => 'id_master_produk']);
    }




}
